baseURL = "https://example.com/"

[Params]
    HeadTitle = "Metta Saketh Srinviasa Rao"
    author = "Metta Saketh Srinviasa Rao"
    info = "This contains all my info"
    avataURL = 'https://github.com/Saketh1997/Saketh.github.io/blob/52c7bea958ba8db7ea6e01dedb9238d916a935f7/images/logos/logotype-a.png'
    social = [
        {name = "Github", url = "https://github.com/Saketh1997", icon = "https://github.com/Saketh1997/Saketh.github.io/blob/main/images/logos/Facebook.png", weight = 1},
        {name = "LinkedIn", url = "https://www.linkedin.com/in/saketh-metta-137a86203/", icon = "https://github.com/Saketh1997/Saketh.github.io/blob/main/images/logos/Linkedin.png", weight = 2}
        ]